# Generated by Django 2.1.7 on 2019-03-05 04:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Salimosinicio', '0003_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='Festivales',
        ),
        migrations.AddField(
            model_name='categorias',
            name='Categorias',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
