# Generated by Django 2.1.7 on 2019-03-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lugares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('Ciudad', models.CharField(max_length=10)),
                ('Direccion', models.CharField(max_length=150)),
                ('Fecha', models.CharField(max_length=150)),
                ('Telefono', models.CharField(max_length=150)),
                ('Pagina', models.CharField(max_length=150)),
            ],
        ),
    ]
